### ISSUE TITLE
recalculate once pymchelper has the number-of-primaries count fixed

### ISSUE THREAD

**Issue by nbassler** [APTG/2022_DCPT_LET_timepix#6]
from #3, pymchelper, once this is fixed https://github.com/DataMedSci/pymchelper/issues/395

**Comment by nbassler** [comment]
Fixed in https://github.com/DataMedSci/pymchelper/issues/718
but triggered another related issue: https://github.com/DataMedSci/pymchelper/issues/722 (WIP)
which needs to be fixed first before recalc.

**Comment by grzanka** [comment]
Done with PR #9
